export const calculator_buttons = [
    { label: 'CE', type: 'delete_last', action: 'deleteLast'  },
    { label: '%', type: 'numbers', action: 'calculatePercentage'},
    { label: 'x²', type: 'numbers', value: '^2' },
    { label: 'AC', type: 'clear_all', action: 'clearAll' },
    { label: '√', type: 'numbers', value: 'sqrt(' },
    { label: 'x!', type: 'numbers', value: '!' },
    { label: 'π', type: 'numbers', value: 'pi' },
    { label: '/', type: 'operation', value: '/' },
    { label: '1', type: 'numbers' },
    { label: '2', type: 'numbers' },
    { label: '3', type: 'numbers' },
    { label: 'x', type: 'operation', value: '*' },
    { label: '4', type: 'numbers' },
    { label: '5', type: 'numbers' },
    { label: '6', type: 'numbers' },
    { label: '+', type: 'operation', value: '+' },
    { label: '7', type: 'numbers' },
    { label: '8', type: 'numbers' },
    { label: '9', type: 'numbers' },
    { label: '-', type: 'operation', value: '-' },
    { label: '0', type: 'numbers', span: 2 },
    { label: '.', type: 'numbers' },
    { label: '=', type: 'operation', action: 'calculateResult' },
];
